Election/Controllers/AdminController.cs
using Election.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Election.Controllers
{
    public class AdminController : Controller
    {
       
        // GET: Admin
        public ActionResult Index()
        {
            ElectionDatabaseEntities dbcand = new ElectionDatabaseEntities();
            ElectionDatabaseEntities0 dbcompte = new ElectionDatabaseEntities0();
            ElectionDatabaseEntities3 dbelect = new ElectionDatabaseEntities3();

            int ncand = dbcand.Candidat.ToList<Candidat>().Count();
            int nelect = dbelect.Electeur.ToList<Electeur>().Count();
            int nadmin = dbcompte.Compte.ToList<Compte>().Count();
            int total = 0;
            foreach (var item in dbcand.Candidat.ToList<Candidat>())
            {
                total = (int)(total + item.voix);
            }

            int v = 0;
            foreach (var item in dbelect.Electeur.ToList<Electeur>())
            {
                if(item.avoter == 1)
                {
                    v = v + 1;
                }
            }

            ViewBag.candidats = ncand;
            ViewBag.electeurs = nelect;
            ViewBag.votant = v;
            ViewBag.admins = nadmin;
            ViewBag.listecand = dbcand.Candidat.ToList<Candidat>();
            ViewBag.totalcandidat = total;
            return View();
        }

        public ActionResult Connexion()
        {
        

            return View();
        }

        // POST: Comptes/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Connexion([Bind(Include = "login,password")] Compte compte)
        {
            ElectionDatabaseEntities0 db = new ElectionDatabaseEntities0();

       

            if (ModelState.IsValid)
            {
                foreach (Compte c in db.Compte.ToList<Compte>())
                {
                    if (c.login.Equals(compte.login) && (c.password.Equals(compte.password)))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ViewBag.message = "Erreur, Login ou mot de passe";
                    }
                }
                //db.Compte.Add(compte);
                //db.SaveChanges();
            }
            
            return View(compte);
        }


    }
}

Election/Controllers/CandidatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Election.Models;

namespace Election.Controllers
{
    public class CandidatsController : Controller
    {
        private ElectionDatabaseEntities db = new ElectionDatabaseEntities();

        // GET: Candidats
        public ActionResult Index()
        {
            return View(db.Candidat.ToList());
        }

        // GET: Candidats/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidat candidat = db.Candidat.Find(id);
            if (candidat == null)
            {
                return HttpNotFound();
            }
            return View(candidat);
        }

        // GET: Candidats/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Candidats/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "prenom,nom,parti,datenaiss")] Candidat candidat)
        {
            if (ModelState.IsValid)
            {
                Candidat c = db.Candidat.ToList<Candidat>().Last();
                candidat.Id = c.Id + 1;
                candidat.voix = 0;
                db.Candidat.Add(candidat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(candidat);
        }

        // GET: Candidats/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidat candidat = db.Candidat.Find(id);
            if (candidat == null)
            {
                return HttpNotFound();
            }
            return View(candidat);
        }

        // POST: Candidats/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,prenom,nom,parti,datenaiss,photo,voix")] Candidat candidat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(candidat);
        }

        // GET: Candidats/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidat candidat = db.Candidat.Find(id);
            if (candidat == null)
            {
                return HttpNotFound();
            }
            return View(candidat);
        }

        // POST: Candidats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Candidat candidat = db.Candidat.Find(id);
            db.Candidat.Remove(candidat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Election/Controllers/ComptesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Election.Models;

namespace Election.Controllers
{
    public class ComptesController : Controller
    {
        private ElectionDatabaseEntities0 db = new ElectionDatabaseEntities0();

        // GET: Comptes
        public ActionResult Index()
        {
            return View(db.Compte.ToList());
        }

        // GET: Comptes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compte compte = db.Compte.Find(id);
            if (compte == null)
            {
                return HttpNotFound();
            }
            return View(compte);
        }

        // GET: Comptes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comptes/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "login,password")] Compte compte)
        {
            if (ModelState.IsValid)
            {
                Compte c= db.Compte.ToList<Compte>().Last();
                compte.Id = c.Id + 1;
                db.Compte.Add(compte);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(compte);
        }

        // GET: Comptes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compte compte = db.Compte.Find(id);
            if (compte == null)
            {
                return HttpNotFound();
            }
            return View(compte);
        }

        // POST: Comptes/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,login,password")] Compte compte)
        {
            if (ModelState.IsValid)
            {
                db.Entry(compte).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(compte);
        }

        // GET: Comptes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Compte compte = db.Compte.Find(id);
            if (compte == null)
            {
                return HttpNotFound();
            }
            return View(compte);
        }

        // POST: Comptes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Compte compte = db.Compte.Find(id);
            db.Compte.Remove(compte);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Election/Controllers/ElecteursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Election.Models;

namespace Election.Controllers
{
    public class ElecteursController : Controller
    {
        private ElectionDatabaseEntities3 db = new ElectionDatabaseEntities3();

        // GET: Electeurs
        public ActionResult Index()
        {
            return View(db.Electeur.ToList());
        }

        // GET: Electeurs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electeur electeur = db.Electeur.Find(id);
            if (electeur == null)
            {
                return HttpNotFound();
            }
            return View(electeur);
        }

        // GET: Electeurs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Electeurs/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,prenom,nom,cni,avoter")] Electeur electeur)
        {
            if (ModelState.IsValid)
            {
                Electeur elec = db.Electeur.ToList<Electeur>().Last();
                
                electeur.Id = elec.Id +1;
                electeur.avoter = 0;
                db.Electeur.Add(electeur);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(electeur);
        }

        // GET: Electeurs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electeur electeur = db.Electeur.Find(id);
            if (electeur == null)
            {
                return HttpNotFound();
            }
            return View(electeur);
        }

        // POST: Electeurs/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,prenom,nom,cni,avoter,candidat")] Electeur electeur)
        {
            if (ModelState.IsValid)
            {
                db.Entry(electeur).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(electeur);
        }

        // GET: Electeurs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electeur electeur = db.Electeur.Find(id);
            if (electeur == null)
            {
                return HttpNotFound();
            }
            return View(electeur);
        }

        // POST: Electeurs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Electeur electeur = db.Electeur.Find(id);
            db.Electeur.Remove(electeur);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Election/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ELECTRO VOTE</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">

    <!-- Vendor CSS Files -->
    @*<link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/icofont/icofont.min.css" rel="stylesheet">
        <link href="assets/vendor/animate.css/animate.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/vendor/nivo-slider/css/nivo-slider.css" rel="stylesheet">
        <link href="assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
        <link href="assets/vendor/venobox/venobox.css" rel="stylesheet">*@
    <link href="~/Content/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/assets/vendor/animate.css/animate.min.css" rel="stylesheet" />
    <link href="~/Content/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/assets/vendor/nivo-slider/css/nivo-slider.css" rel="stylesheet" />
    <link href="~/Content/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet" />

    <link href="~/Content/assets/vendor/venobox/venobox.min.css" rel="stylesheet" />

    <!-- Template Main CSS File <link href="assets/css/style.css" rel="stylesheet">-->
    <link href="~/Content/assets/vendor/icofont/icofont.min.css" rel="stylesheet" />

    <link href="~/Content/assets/css/style.css" rel="stylesheet" />
</head>
<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex">

            <div class="logo mr-auto">
                <h1 class="text-light"><a @Html.ActionLink("<", "Index", "Home") ><span>Electro</span>Vote</a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="active">
                        @Html.ActionLink("Accueil", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Election", "Election", "Home")
                    </li>
                    <li>
                    <li>
                        @Html.ActionLink("Administration", "Connexion", "Admin")
                    </li>
                    <li>
                        @Html.ActionLink("Contact", "Contact", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("À propos de", "About", "Home")
                    </li>
                    <li class="btn btn-info">@Html.ActionLink("Connexion", "Connexion", "Admin")</li>

                </ul>
            </nav><!-- .nav-menu -->

        </div>
    </header><!-- End Header -->

    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ELECTRONIC VOTE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Election", "Election", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Administration", "Connexion", "Admin")</li>
                </ul>

            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="bg-light text-center text-lg-start">
            <!-- Grid container -->
            <div class="container p-4 pb-0">
                <form action="">
                    <!--Grid row-->
                    <div class="row">
                        <!--Grid column-->
                        <div class="col-auto mb-4 mb-md-0">
                            <p class="pt-2"><strong>S'inscrire au Newsletter</strong></p>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-md-5 col-12 mb-4 mb-md-0">
                            <!-- Email input -->
                            <div class="form-outline mb-4">
                                <input type="email" id="form5Example2" class="form-control" />
                                <label class="form-label" for="form5Example2">Adresse email</label>
                            </div>
                        </div>
                        <!--Grid column-->
                        <!--Grid column-->
                        <div class="col-auto mb-4 mb-md-0">
                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary mb-4">S'inscrire</button>
                        </div>
                        <!--Grid column-->
                    </div>
                    <!--Grid row-->
                </form>
            </div>
            <!-- Grid container -->
            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
                © 2021 Copyright: ElectroVote concu par Habibou DIEDHIOU et El Hadji Code Ndiaye
               
            </div>
            <!-- Copyright -->
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Election/Views/Shared/_admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Style.css" rel="stylesheet" />\

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ELECTRONIC VOTE", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Candidat", "Index", "Candidats")</li>
                    <li>@Html.ActionLink("Electeur", "Index", "Electeurs")</li>
                    <li>@Html.ActionLink("Compte", "Index", "Comptes")</li>
                </ul>

                <a href="Admin/Connexion" class="btn btn-warning" style="float:right; margin:10px">Deconnexion</a>
            </div>
        </div>
    </div>
        
    <div class="container body-content">

        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="sidebar-nav">
                        <div class="navbar navbar-default" role="navigation">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <span class="visible-xs navbar-brand">Sidebar menu</span>
                            </div>
                            <div class="navbar-collapse collapse sidebar-navbar-collapse">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="/Admin">TABLEAU DE BORD</a></li>
                                    <li>@Html.ActionLink("Candidat", "Index", "Candidats")</li>
                                    <li>@Html.ActionLink("Electeur", "Index", "Electeurs")</li>
                                    <li>@Html.ActionLink("Compte", "Index", "Comptes")</li>
                                </ul>
                            </div><!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    @RenderBody()
                </div>
            </div>
        </div>


        <hr />`
        <footer>
            <p>&copy; @DateTime.Now.Year -ElectroVote par Habibou DIEDHIOU et El Hadji Code Ndiaye</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>